# name: deploy to kubernetes


# on:
#   push:
#     branches:
#       -"Complete -CI/CD-With-Terraform-GKE"

# env:
#   GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID}}
#   TF_STATE_BUCKET_NAME: *{{secrets.GCP_TF_STATE_BUCKET}}

# jobs:
#   deploy:
#   runs-on: ubuntu-latest
#   env:
#     IMAGE-TAG: ${{github.sha}}
#   permissions:
#     content: 'read'
#     id-token: 'write'
  
#   steps:
#     -uses: 'actions/checkout@v3'
#     -id: 'auth'
#       name: 'Authenticate to Google Cloud'
#       uses: 'google-github-actions/auth@v1'
#       with:
#         token_format: 'access_token'
#         workload_identity_provider: 'projects/805037304914/locations/global/workloadIdentityPools/k8s-pool/providers/k8s-provider'
#         service_account: 'souhail-gke-sa@capable-land-467617-s5.iam.gserviceaccount.com'
#     -uses : 'google-github-actions/setup-gcloud@v1'
#     -name: Docker auth
#       run: gcloud auth configure-docker
#     -name: build and push docker image
#       run: |
#         docker build -it us.gcr.io/$GCP_PROJECT_ID/nodeappimage:$IMAGE_TAG
#         docker push us.gcr.io/$GCP_PROJECT_ID/nodeappimage:$IMAGE_TAG
#       working-directory: ./nodeapp
#     -uses: hashicorp/setup-terraform@v2  #already action ongithib runner of terraform
#     -name: Terraform init
#       run: terraform init -backend-config ="bucket=$TF_STATE_BUCKET_NAME" -backend-config="prefix=k8s"
#       working-directory: ./terraform
#     -name: Terraform plan
#       run: |
#         terraform plan \
#         -var= "region=us=us-central1" \
#         -var= "project_id=$GCP_PROJECT_ID" \
#         -var="container_image= us.gcr.io/$GCP_PROJECT_ID/nodeappimage:$IMAGE_TAG 
#         -out=PLAN
#     -name: terraform apply
#       run: terraform apply PLAN  

name: Deploy to Kubernetes

on:
  push:
    branches:
      - "Complete-CI/CD-With-Terraform-GKE"

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  TF_STATE_BUCKET_NAME: ${{ secrets.GCP_TF_STATE_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/805037304914/locations/global/workloadIdentityPools/k8s-pool/providers/k8s-provider'
          service_account: 'souhail-gke-sa@capable-land-467617-s5.iam.gserviceaccount.com'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Docker auth
        run: gcloud auth configure-docker

      - name: Build and push docker image
        run: |
          docker build -t us.gcr.io/$GCP_PROJECT_ID/nodeappimage:$IMAGE_TAG .
          docker push us.gcr.io/$GCP_PROJECT_ID/nodeappimage:$IMAGE_TAG
        working-directory: ./nodeapp

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        run: terraform init -backend-config="bucket=$TF_STATE_BUCKET_NAME" -backend-config="prefix=k8s"
        working-directory: ./terraform

      - name: Terraform plan
        run: |
          terraform plan \
          -var="region=us-central1" \
          -var="project_id=$GCP_PROJECT_ID" \
          -var="container_image=us.gcr.io/$GCP_PROJECT_ID/nodeappimage:$IMAGE_TAG" \
          -out=PLAN
        working-directory: ./terraform

      - name: Terraform apply
        run: terraform apply PLAN
        working-directory: ./terraform
